services:
   nginx:
    container_name: login-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs/selfsigned.crt:/etc/nginx/certs/selfsigned.crt
      - ./certs/selfsigned.key:/etc/nginx/certs/selfsigned.key